# Generated by Django 5.1.4 on 2025-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_reverse',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
