# Generated by Django 5.1.4 on 2025-01-28 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hardwaretype_product_hardware_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
