# Generated by Django 5.1.4 on 2025-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used, like new'), ('used', 'Used'), ('torn', 'Torn')], default='new', max_length=50),
        ),
    ]
